  run_tests:
    needs: [detect_project, build_filesystem]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_type: [test_1, test_2, test_3]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: esp32-firmware-binary
          path: .

      - name: Test with Wokwi
        uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CLI_TOKEN }}
          scenario: 'scenarios/${{ needs.detect_project.outputs.project_folder }}/${{ matrix.test_type }}.yaml'
          timeout: 30000
          expect-text: 'Teste finalizado com sucesso.'
